<?php
/**
 * 
 * @admin ~~// this is the file for all arrays
 * 
 */
if ( ! defined( 'ABSPATH' ) ) exit;

// ====================================================
// For new show
$whatsNew = [
    [
        'img'=>'../../assets/admin/dashboard/images/small-logo.png',
        'name'=>esc_html__('Special Day Offer',BWDEB_PLUGIN_TD),
        'desc'=>esc_html__('Creates customizable special day offer for woocommerce.',BWDEB_PLUGIN_TD),
    ],
    [
        'img'=>'../../assets/admin/dashboard/images/small-logo.png',
        'name'=>esc_html__('Header Builder',BWDEB_PLUGIN_TD),
        'desc'=>esc_html__('Creates customizable headers with drag-and-drop ease.',BWDEB_PLUGIN_TD),
    ],
    [
        'img'=>'../../assets/admin/dashboard/images/small-logo.png',
        'name'=>esc_html__('Footer Effects',BWDEB_PLUGIN_TD),
        'desc'=>esc_html__('Creates customizable footers with drag-and-drop ease.',BWDEB_PLUGIN_TD),
    ],
    [
        'img'=>'../../assets/admin/dashboard/images/small-logo.png',
        'name'=>esc_html__('Random Builder',BWDEB_PLUGIN_TD),
        'desc'=>esc_html__('Random Image with responsive and modern designs.',BWDEB_PLUGIN_TD),
    ],
    [
        'img'=>'../../assets/admin/dashboard/images/small-logo.png',
        'name'=>esc_html__('Live Copy',BWDEB_PLUGIN_TD),
        'desc'=>esc_html__('Copy-paste Elementor designs across sites easily.',BWDEB_PLUGIN_TD),
    ],
    [
        'img'=>'../../assets/admin/dashboard/images/small-logo.png',
        'name'=>esc_html__('Vertical Split Slideshow',BWDEB_PLUGIN_TD),
        'desc'=>esc_html__('Create vertical split-screen image slideshows.',BWDEB_PLUGIN_TD),
    ],
    [
        'img'=>'../../assets/admin/dashboard/images/small-logo.png',
        'name'=>esc_html__('Advanced Posts Tab',BWDEB_PLUGIN_TD),
        'desc'=>esc_html__('Display posts in tabbed, organized layout.',BWDEB_PLUGIN_TD),
    ]
];
// ====================================================
// For general
$generalWidgets = [
    [
        'name'=>esc_html__('Meet The Team',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-meet-the-team',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/mtt_documentation/',
        'demo'=>'https://bestwpdeveloper.com/meet-the-team',
        'video'=>'https://youtu.be/pcCObKvhhrk',
        'free_pro'=>true,
        'new'=>false
    ],
    [
        'name'=>esc_html__('Testimonials',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-testimonials',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bwdt-documentation/',
        'demo'=>'https://bestwpdeveloper.com/testimonial-addon-for-elementor',
        'video'=>'https://youtu.be/-8Amde3m_m0',
        'free_pro'=>true,
        'new'=>false
    ],
    [
        'name'=>esc_html__('Creative Button',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-creative-button',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bcb_documentation/',
        'demo'=>'https://bestwpdeveloper.com/creative-button',
        'video'=>'https://youtu.be/MH7n_vCnaIw',
        'free_pro'=>true,
        'new'=>false
    ],
    [
        'name'=>esc_html__('Accordion',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-accordion',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/ba_documentation/',
        'demo'=>'https://bestwpdeveloper.com/accordion-addon-for-elementor',
        'video'=>'https://youtu.be/LTNVB6LJ88Y',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Masking Effect',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-masking-effect',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bme_documentation/',
        'demo'=>'https://bestwpdeveloper.com/bwd-masking-effect',
        'video'=>'https://youtu.be/vPXPx6rAx2w',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Service Showcase',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-service-showcase',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bss_documentation/',
        'demo'=>'https://bestwpdeveloper.com/service-addon-for-elementor',
        'video'=>'https://youtu.be/Q2Gb1ouZhmc',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Promo Box',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-promo-box',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bpb_documentation/',
        'demo'=>'https://bestwpdeveloper.com/promo-box',
        'video'=>'https://youtu.be/DUb42fYHajE',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Service Flip Box',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-service-flip-box',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bfb_documentation/',
        'demo'=>'https://bestwpdeveloper.com/flip-box-addon-for-service',
        'video'=>'https://youtu.be/1oOcufI_zVk',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Flip Box Carousel',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-flip-box-carousel',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/flip-box-carousel',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Step Flip Box',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-step-flip-box',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/flip-box-addon-for-step',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Team Flip Box',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-team-flip-box',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/flip-box-addon-for-team',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Map Masking',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-map-masking',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bmm_documentation/',
        'demo'=>'https://bestwpdeveloper.com/bwd-map-masking',
        'video'=>'https://youtu.be/hZqa4C1F2f4',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Creative List',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-creative-list',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bcl_documentation/',
        'demo'=>'https://bestwpdeveloper.com/creative-list-addon-for-elementor',
        'video'=>'https://youtu.be/PrR1zSj3oYE',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Dual Heading',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-dual-heading',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bdh_documentation/',
        'demo'=>'https://bestwpdeveloper.com/dual-heading-addon-for-elementor',
        'video'=>'https://youtu.be/LxJLKn64NTw',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Back To Top',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-back-to-top',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bub_documentation/',
        'demo'=>'https://bestwpdeveloper.com/back-to-top-addon-for-elementor',
        'video'=>'https://youtu.be/KxoIqQMRtaI',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Call To Action',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-call-to-action',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bac_documentation/',
        'demo'=>'https://bestwpdeveloper.com/call-to-action-for-elementor',
        'video'=>'https://youtu.be/vdVkqTTbsj0',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Icon Box',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-icon-box',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bib_documentation/',
        'demo'=>'https://bestwpdeveloper.com/icon-box-addon-for-elementor',
        'video'=>'https://youtu.be/UcZGtXkCxQw',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Dual Button',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-dual-button',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bdb_documentation/',
        'demo'=>'https://bestwpdeveloper.com/dual-button-addon-for-elementor',
        'video'=>'https://youtu.be/vzfV9sg82GA',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Awesome Step',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-awesome-step',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bas_documentation/',
        'demo'=>'https://bestwpdeveloper.com/step-addon-for-elementor',
        'video'=>'https://youtu.be/vgEbdBGmL0I',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Counter',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-counter',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bc_documentation/',
        'demo'=>'https://bestwpdeveloper.com/counter-addon-for-elementor',
        'video'=>'https://youtu.be/rMYs56zi9mU',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Image Hover Effect',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-image-hover-effect',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bihe_documentation/',
        'demo'=>'https://bestwpdeveloper.com/image-hover-effect-addon-for-elementor',
        'video'=>'https://youtu.be/wGzOjBawVks',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Countdown',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-countdown',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bcd_documentation/',
        'demo'=>'https://bestwpdeveloper.com/count-down-addon-for-elementor',
        'video'=>'https://youtu.be/Yq9d0LqljFM',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Animated Heading',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-animated-heading',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bah_documentation/',
        'demo'=>'https://bestwpdeveloper.com/animated-heading',
        'video'=>'https://youtu.be/pAsB3czMJpk',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Filterable Gallery',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-filterable-gallery',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bfg_documentation/',
        'demo'=>'https://bestwpdeveloper.com/filterable-gallery-for-elementor',
        'video'=>'https://youtu.be/mPbbrVy6Peo',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Pricing Table',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-pricing-table',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bpt_documentation/',
        'demo'=>'https://bestwpdeveloper.com/pricing-table-addon-for-elementor',
        'video'=>'https://youtu.be/1TPxbcLMIlg',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Social Icon',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-social-icon',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bsi_documentation/',
        'demo'=>'https://bestwpdeveloper.com/social-icon-addon-for-elementor',
        'video'=>'https://youtu.be/zZBjFeyfMz8',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Creative Tab',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-creative-tab',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/ct_documentation/',
        'demo'=>'https://bestwpdeveloper.com/creative-tabs-addon-for-elementor',
        'video'=>'https://youtu.be/ND7HAJaM540',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Author Bio',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-author-bio',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bab_documentation/',
        'demo'=>'https://bestwpdeveloper.com/author-bio-addon-for-elementor',
        'video'=>'https://youtu.be/n59aK0MVhq0',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Animated Link',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-animated-link',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bal_documentation/',
        'demo'=>'https://bestwpdeveloper.com/animated-link-plugin-for-elementor',
        'video'=>'https://youtu.be/QrRmubDyYO0',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Business Hours',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-business-hours',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bbh_documentation/',
        'demo'=>'https://bestwpdeveloper.com/business-hours-addon-for-elementor',
        'video'=>'https://youtu.be/Dv3o4xeFKt8',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Image Shape',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-image-shape',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bis_documentation/',
        'demo'=>'https://bestwpdeveloper.com/bwd-image-shape',
        'video'=>'https://youtu.be/MXQ2stKp1TM',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Fancy Heading',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-fancy-heading',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bfh_documentation/',
        'demo'=>'https://bestwpdeveloper.com/fancy-heading-addon-for-elementor',
        'video'=>'https://youtu.be/s4vv9k59YIU',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Progress Bar',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-progress-bar',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/pb_documentation/',
        'demo'=>'https://bestwpdeveloper.com/progress-bar-addon-for-elementor',
        'video'=>'https://youtu.be/Nd9-s0LUScY',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Image Accordion',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-image-accordion',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bia_documentation/',
        'demo'=>'https://bestwpdeveloper.com/image-accordion',
        'video'=>'https://youtu.be/0PeOVgMsE8U',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Image Compare',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-image-compare',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bic_documentation/',
        'demo'=>'https://bestwpdeveloper.com/image-compare',
        'video'=>'https://youtu.be/VaHUBjapJo4',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Timeline',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-timeline',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bit_documentation/',
        'demo'=>'https://bestwpdeveloper.com/timeline',
        'video'=>'https://youtu.be/DwUDn5LoHbw',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Blockquote',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-blockquote',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bbq_documentation/',
        'demo'=>'https://bestwpdeveloper.com/blockquote',
        'video'=>'https://youtu.be/9uTAOUmMVIY',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Video Popup',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-video-popup',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bvp_documentation/',
        'demo'=>'https://bestwpdeveloper.com/video-popup',
        'video'=>'https://youtu.be/ux_ccVc4jp0',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Image Stack Group',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-image-stack-group',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/isg_documentation/',
        'demo'=>'https://bestwpdeveloper.com/image-stack-group',
        'video'=>'https://youtu.be/-rFwAjptPNU',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Masking Video',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-masking-video',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bmv_documentation/',
        'demo'=>'https://bestwpdeveloper.com/masking-video-addon-for-elementor',
        'video'=>'https://youtu.be/bKFpRTfJGXU',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Image Swap',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-image-swap',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/is_documentation/',
        'demo'=>'https://bestwpdeveloper.com/image-swap',
        'video'=>'https://youtu.be/Nd7vTs4jf2Y',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Profile Card',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-profile-card',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bpc_documentation/',
        'demo'=>'https://bestwpdeveloper.com/profile-card-addon-for-elementor',
        'video'=>'https://youtu.be/xsL9Y5rKNrA',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Photo Stack',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-photo-stack',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/ps_documentation/',
        'demo'=>'https://bestwpdeveloper.com/photo-stack-plugin-for-elementor-page-builder',
        'video'=>'https://youtu.be/sBGZHB1bh0g',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Image Scroll',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-image-scroll',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/biscrol_documentation/',
        'demo'=>'https://bestwpdeveloper.com/image-scroll-elementor-addon',
        'video'=>'https://youtu.be/DN_QkzBGaYE',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('I Hover',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-ihover',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/ie_documentation/',
        'demo'=>'https://bestwpdeveloper.com/ihover',
        'video'=>'https://youtu.be/bnB-TwipphA',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Webinar Info',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-webinar-info',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bwi_documentation/',
        'demo'=>'https://bestwpdeveloper.com/webinar-info-addon-for-elementor',
        'video'=>'https://youtu.be/BbhoRwCvRLs',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Circle Info',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-circle-info',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/interactive-circle-infographic',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Coupon Code',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-coupon-code',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bcc_documentation/',
        'demo'=>'https://bestwpdeveloper.com/elementor-coupon-code',
        'video'=>'https://youtu.be/NDnhR6mryQk',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Unique Headers',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-unique-headers',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/tuh_documentation/',
        'demo'=>'https://bestwpdeveloper.com/elementor-header',
        'video'=>'https://youtu.be/mzuUEsokwfg',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Click to Contact',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-click-to-contact',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/ctc_documentation/',
        'demo'=>'https://bestwpdeveloper.com/plugins/click-to-contact',
        'video'=>'https://youtu.be/8lIDR4E9eZ0',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Data Table',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-data-table',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/dt_documentation/',
        'demo'=>'https://bestwpdeveloper.com/elementor-data-table',
        'video'=>'https://youtu.be/qWfl8tWiUi4',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Contact Form 7 Styler',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-contact-form-7-styler',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bwdcs_documentation/',
        'demo'=>'https://bestwpdeveloper.com/contact-form-7-styler',
        'video'=>'https://youtu.be/OGbvLL0FYeU',
        'free_pro'=>false,
        'new'=>true,
    ],
    [
        'name'=>esc_html__('Logo Carousel',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-logo-carousel',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/brand-logo-carousel',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Logo Grid',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-logo-grid',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/brand-logo-grid',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Logo Filter',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-logo-filter',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/brand-logo-filter',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Team Slider',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-team-carousel',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/tc_documentation/',
        'demo'=>'https://bestwpdeveloper.com/team-member-carousel',
        'video'=>'https://youtu.be/9pJjXA4WJEo',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Code Highlighter',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-code-highlighter',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/ch_documentation/',
        'demo'=>'https://bestwpdeveloper.com/code-highlighter',
        'video'=>'https://youtu.be/_LiqhtLp-AM',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Breadcrumb',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-breadcrumb',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bb_documentation/',
        'demo'=>'https://bestwpdeveloper.com/breadcrumb',
        'video'=>'https://youtu.be/63LVEmx82kc',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Info Download Button',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-info-download-button',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/indb_documentation/',
        'demo'=>'https://bestwpdeveloper.com/info-download-button',
        'video'=>'https://youtu.be/IonUxHpHkGs',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Effective Pre Loader',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-effective-pre-loader',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bep_documentation/',
        'demo'=>'https://bestwpdeveloper.com/pre-loader',
        'video'=>'https://youtu.be/45ki61ZB-68',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Social Share',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-social-share',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bwdss_documentation/',
        'demo'=>'https://bestwpdeveloper.com/social-share',
        'video'=>'https://youtu.be/6w_cxs-eOgw',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Background Switcher',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-background-switcher',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bbs_documentation/',
        'demo'=>'https://bestwpdeveloper.com/background-switcher',
        'video'=>'https://youtu.be/Szp42b_C6yE',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Content Switcher',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-content-switcher',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/content-switcher',
        'video'=>'https://youtu.be/5VLmFs5jUA4',
        'free_pro'=>true,
        'new'=>false,
    ],
    // Free end
    [
        'name'=>esc_html__('Honeycombs',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-honeycombs',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/honeycombs',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false
    ],
    [
        'name'=>esc_html__('Popup',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-popup',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/popup-elementor-addon',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false
    ],
    [
        'name'=>esc_html__('Advanced Slider',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-advanced-slider',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/advanced-slider',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false
    ],
    [
        'name'=>esc_html__('Team Carousel',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-team-carousel2',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/tc_documentation/',
        'demo'=>'https://bestwpdeveloper.com/team-member-carousel',
        'video'=>'https://youtu.be/9pJjXA4WJEo',
        'free_pro'=>true,
        'new'=>false,
    ],
    [
        'name'=>esc_html__('Anything Slide',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-slide-anything',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/anything-slide',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false
    ],
    [
        'name'=>esc_html__('Image Hotspot',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-image-hotspot',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/image-hotspot',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false
    ],
    [
        'name'=>esc_html__('Unfold Content',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-unfold',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/unfold-content',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false
    ],
    [
        'name'=>esc_html__('Effective Lottie Animation',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-lottie-animation',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/effective-lottie-animation',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false
    ],
    [
        'name'=>esc_html__('Bar Chart',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-bar-chart',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/bar-chart',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false
    ],
    [
        'name'=>esc_html__('Lord Icon',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-lord-icon',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/lord-icon',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false
    ],
    [
        'name'=>esc_html__('Card Flipper Pro',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-cart-flipper',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/card-flipper-pro',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false
    ],
    [
        'name'=>esc_html__('Ajax Data Table',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-ajax-data-table',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/ajax-data-table',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false
    ],
    [
        'name'=>esc_html__('Content Switcher Plus',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-con-swi-pls',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/content-switcher-plus',
        'video'=>'https://youtu.be/5VLmFs5jUA4',
        'free_pro'=>false,
        'new'=>false
    ],
    [
        'name'=>esc_html__('Image Reveal Animation',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-img-rev-widg',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/image-reveal-animation',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false
    ],
    [
        'name'=>esc_html__('Image Unfold Kit',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-img-unfold-kit',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/image-unfold-kit',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false
    ],
    [
        'name'=>esc_html__('Modern Feature List',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-modern-feature-list',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/modern-feature-list',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false
    ],
    [
        'name'=>esc_html__('Offcanvas Slide Magic',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-offcanvasmagic',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/offcanvas-slide-magic',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false
    ],
    [
        'name'=>esc_html__('Private Content Locker',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-privacy-content-locker',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/private-content-locker',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false
    ],
    [
        'name'=>esc_html__('Clear PDF View',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-viewpdf',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/clear-pdf-view',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false
    ],
    [
        'name'=>esc_html__('Progress Master Kit',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-progress-master-kit',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/progress-master-kit',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false
    ],
    [
        'name'=>esc_html__('Restaurant Price Menu',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-restaurant-price-menu',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/restaurant-price-menu',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false
    ],
    [
        'name'=>esc_html__('Sales Promotion Offer',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-sales-promotion-offer',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/sales-promotion-offer',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false
    ],
    [
        'name'=>esc_html__('Showcase Your Profile',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-profile-showcas',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/showcase-your-profile',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false
    ],
    [
        'name'=>esc_html__('Tooltip Mastery',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-plugin-tooltip-mastery',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/tooltip-mastery',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false
    ],
    [
        'name'=>esc_html__('Employee Profile Identity',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-employee-profile-identity',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/employee-profile-identity',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false
    ],
    [
        'name'=>esc_html__('Horizontal Timeline Slider',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-horizontal-timeline-slider',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/horizontal-timeline-slider',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false
    ],
    [
        'name'=>esc_html__('Showcase Product Features',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-product-features-w',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/Showcase-Product-Features',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false
    ],
    [
        'name'=>esc_html__('360 Rotation View',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-threesixty-rotation-view',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/threesixty-rotation-view',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false
    ],
    [
        'name'=>esc_html__('FAQ',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-widget-template',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/bwd-faq',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false
    ],
    [
        'name'=>esc_html__('Pricing Scheme Switcher',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-pssx',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/pricing-scheme-switcher',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false
    ],
    [
        'name'=>esc_html__('Bio About Maker',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-blmx1',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/bio-about-maker',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false
    ],
    [
        'name'=>esc_html__('Bio Link Maker',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-blmx2',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/bio-link-maker',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false
    ],
    [
        'name'=>esc_html__('Bio Social Maker',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-blmx3',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/bio-social-maker',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false
    ],
    [
        'name'=>esc_html__('Sticky Video Prime',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-svpx',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/sticky-video-prime',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false
    ],
    [
        'name'=>esc_html__('Tabify Xpert Suite',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-txsx',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/tabify-xpert-suite',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false
    ],
    [
        'name'=>esc_html__('Vertical Split Slideshow',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-vsix',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/vertical-split-slideshow',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false
    ],
    [
        'name'=>esc_html__('Random Image',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-random-image',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/random-image/',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>true
    ],
    [
        'name'=>esc_html__('Mega Menu',BWDEB_PLUGIN_TD),
        'id'=>'bwdeb-mega-menu',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/mega-menu/',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>true
    ]
];
// ====================================================
// For CV Builder widgets
$cvWidgets = [
    [
        'name' => esc_html__('Builder', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-plugin-cv-builder',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/bcvb_documentation/',
        'demo' => 'https://bestwpdeveloper.com/cv-builder-plugin-for-elementor/',
        'video' => 'https://youtu.be/EeuQyTVc0Ig',
        'free_pro' => false,
        'new' => false,
    ],
    [
        'name' => esc_html__('About', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-plugin-cv-about',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/bcvb_documentation/',
        'demo' => 'https://bestwpdeveloper.com/cv-builder-plugin-for-elementor/',
        'video' => 'https://youtu.be/EeuQyTVc0Ig',
        'free_pro' => false,
        'new' => false,
    ],
    [
        'name' => esc_html__('Contact', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-plugin-cv-contact',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/bcvb_documentation/',
        'demo' => 'https://bestwpdeveloper.com/cv-builder-plugin-for-elementor/',
        'video' => 'https://youtu.be/EeuQyTVc0Ig',
        'free_pro' => false,
        'new' => false,
    ],
    [
        'name' => esc_html__('Education', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-plugin-cv-education',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/bcvb_documentation/',
        'demo' => 'https://bestwpdeveloper.com/cv-builder-plugin-for-elementor/',
        'video' => 'https://youtu.be/EeuQyTVc0Ig',
        'free_pro' => false,
        'new' => false,
    ],
    [
        'name' => esc_html__('Experience', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-plugin-cv-experience',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/bcvb_documentation/',
        'demo' => 'https://bestwpdeveloper.com/cv-builder-plugin-for-elementor/',
        'video' => 'https://youtu.be/EeuQyTVc0Ig',
        'free_pro' => false,
        'new' => false,
    ],
    [
        'name' => esc_html__('Footer', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-plugin-cv-footer',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/bcvb_documentation/',
        'demo' => 'https://bestwpdeveloper.com/cv-builder-plugin-for-elementor/',
        'video' => 'https://youtu.be/EeuQyTVc0Ig',
        'free_pro' => false,
        'new' => false,
    ],
    [
        'name' => esc_html__('Header', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-plugin-cv-header',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/bcvb_documentation/',
        'demo' => 'https://bestwpdeveloper.com/cv-builder-plugin-for-elementor/',
        'video' => 'https://youtu.be/EeuQyTVc0Ig',
        'free_pro' => false,
        'new' => false,
    ],
    [
        'name' => esc_html__('Hobby', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-plugin-cv-hobby',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/bcvb_documentation/',
        'demo' => 'https://bestwpdeveloper.com/cv-builder-plugin-for-elementor/',
        'video' => 'https://youtu.be/EeuQyTVc0Ig',
        'free_pro' => false,
        'new' => false,
    ],
    [
        'name' => esc_html__('Language', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-plugin-cv-language',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/bcvb_documentation/',
        'demo' => 'https://bestwpdeveloper.com/cv-builder-plugin-for-elementor/',
        'video' => 'https://youtu.be/EeuQyTVc0Ig',
        'free_pro' => false,
        'new' => false,
    ],
    [
        'name' => esc_html__('Reference', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-plugin-cv-reference',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/bcvb_documentation/',
        'demo' => 'https://bestwpdeveloper.com/cv-builder-plugin-for-elementor/',
        'video' => 'https://youtu.be/EeuQyTVc0Ig',
        'free_pro' => false,
        'new' => false,
    ],
    [
        'name' => esc_html__('Skill', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-plugin-cv-skill',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/bcvb_documentation/',
        'demo' => 'https://bestwpdeveloper.com/cv-builder-plugin-for-elementor/',
        'video' => 'https://youtu.be/EeuQyTVc0Ig',
        'free_pro' => false,
        'new' => false,
    ]
];
// ====================================================
// For hero section
$heroWidgets = array();
for ($i = 1; $i <= 13; $i++) {
    $heroWidgets[] = array('id' => 'bwdeb-check-hero-widget' . $i);
}
// ====================================================
// For blogs widgets
$postWidgets = [
    [
        'name' => esc_html__('Post Grid', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-plugin-post-grid',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/bpg_documentation/',
        'demo' => 'https://bestwpdeveloper.com/post-grid-elementor-addon',
        'video' => 'https://youtu.be/yTS8QLQ21Wc',
        'free_pro' => true,
        'new' => false,
    ],
    [
        'name' => esc_html__('Post List', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-plugin-post-list',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/bpl_documentation/',
        'demo' => 'https://bestwpdeveloper.com/blog-post-list',
        'video' => 'https://youtu.be/U4mNqSR7BnM',
        'free_pro' => true,
        'new' => false,
    ],
    [
        'name' => esc_html__('Post Tiles', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-plugin-post-tiles',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/pt_documentation/',
        'demo' => 'https://bestwpdeveloper.com/post-tiles',
        'video' => 'https://youtu.be/vInzwBMk-8g',
        'free_pro' => true,
        'new' => false,
    ],
    [
        'name' => esc_html__('Post Accordion', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-plugin-post-accordion',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/bpa_documentation/',
        'demo' => 'https://bestwpdeveloper.com/blog-post-accordions',
        'video' => 'https://youtu.be/zEQX5bs-ixA',
        'free_pro' => true,
        'new' => false,
    ],
    [
        'name' => esc_html__('Post Timeline', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-plugin-post-timeline',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/bwdpt_documentation/',
        'demo' => 'https://bestwpdeveloper.com/post-timeline',
        'video' => 'https://youtu.be/uG-zfqFMp5Q',
        'free_pro' => true,
        'new' => true,
    ],
    [
        'name' => esc_html__('Masonry Blog Post', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-plugin-masonary-blog-post',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/mbp_documentation/',
        'demo' => 'https://bestwpdeveloper.com/masonry-blog-post',
        'video' => 'https://youtu.be/9gZO7VJDX_s',
        'free_pro' => true,
        'new' => false,
    ],
    [
        'name' => esc_html__('Post Image Accordion', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-plugin-post-image-accordion',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/bpia_documentation/',
        'demo' => 'https://bestwpdeveloper.com/post-image-accordion',
        'video' => 'https://youtu.be/b1akfGvkAjU',
        'free_pro' => true,
        'new' => false,
    ],
    [
        'name' => esc_html__('Effective Post Slider', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-plugin-single-post-slider',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/eps_documentation/',
        'demo' => 'https://bestwpdeveloper.com/effective-post-slider',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => true,
        'new' => false,
    ],
    [
        'name' => esc_html__('News Ticker', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-plugin-news-ticker',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/nt_documentation/',
        'demo' => 'https://bestwpdeveloper.com/news-ticker/',
        'video' => 'https://youtu.be/wYAgOsXuAGo',
        'free_pro' => true,
        'new' => true,
    ],
    [
        'name' => esc_html__('Creative Post Carousel', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-plugin-creative-post-carousel',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/bwdpc_documentation/',
        'demo' => 'https://bestwpdeveloper.com/post-carousel',
        'video' => 'https://youtu.be/0JlzpM3vY68',
        'free_pro' => false,
        'new' => false,
    ],
    [
        'name' => esc_html__('Post Prestige Portfolio', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-post-prestige-portfolio',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/ppp_documentation/',
        'demo' => 'https://bestwpdeveloper.com/post-prestige-portfolio/',
        'video' => 'https://youtu.be/AfNyvVDL_Ds',
        'free_pro' => false,
        'new' => true,
    ],
    [
        'name' => esc_html__('Advanced Posts Tab', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-apostst',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/apt_documentation/',
        'demo' => 'https://bestwpdeveloper.com/advanced-posts-tab/',
        'video' => 'https://youtu.be/FwM_qglwP_E',
        'free_pro' => false,
        'new' => false,
    ]
];
// ====================================================
// For woocommerce widgets
$productWidgets = [
    [
        'name' => esc_html__('Product Grid', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-plugin-product-grid',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/bcpg_documentation/',
        'demo' => 'https://bestwpdeveloper.com/woocommerce-product-grid-addon-for-elementor',
        'video' => 'https://youtu.be/o5gMNFCSfFk',
        'free_pro' => true,
        'new' => false,
    ],
    [
        'name' => esc_html__('Product List', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-plugin-product-list',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/wcpl_documentation/',
        'demo' => 'https://bestwpdeveloper.com/creative-products-list',
        'video' => 'https://youtu.be/pTYzZmbgr6g',
        'free_pro' => true,
        'new' => false,
    ],
    [
        'name' => esc_html__('Product Tiles', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-plugin-product-tiles',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/wpt_documentation/',
        'demo' => 'https://bestwpdeveloper.com/product-tiles',
        'video' => 'https://youtu.be/ODg6BasPxc0',
        'free_pro' => true,
        'new' => false,
    ],
    [
        'name' => esc_html__('Product Carousel', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-plugin-product-carousel',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/gpc_documentation/',
        'demo' => 'https://bestwpdeveloper.com/product-carousel',
        'video' => 'https://youtu.be/keVdF2gEiok',
        'free_pro' => true,
        'new' => false,
    ],
    [
        'name' => esc_html__('Product Category Grid', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-plugin-product-category-grid',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/pcg_documentation/',
        'demo' => 'https://bestwpdeveloper.com/woocommerce-product-category-grid',
        'video' => 'https://youtu.be/5k5UWXw85ec',
        'free_pro' => true,
        'new' => false,
    ],
    [
        'name' => esc_html__('Product Category Tiles', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-plugin-product-category-tiles',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/wpct_documentation/',
        'demo' => 'https://bestwpdeveloper.com/woocommerce-product-category-tiles',
        'video' => 'https://youtu.be/HN317B4tSoI',
        'free_pro' => true,
        'new' => true,
    ],
    [
        'name' => esc_html__('Product Accordion', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-plugin-product-accordion',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/wpa_documentation/',
        'demo' => 'https://bestwpdeveloper.com/product-accordion',
        'video' => 'https://youtu.be/zFz98rgw0sI',
        'free_pro' => true,
        'new' => false,
    ],
    [
        'name' => esc_html__('Product Image Accordion', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-plugin-product-image-accordion',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/wpia_documentation/',
        'demo' => 'https://bestwpdeveloper.com/product-image-accordion',
        'video' => 'https://youtu.be/z8vXk1oo1HQ',
        'free_pro' => true,
        'new' => false,
    ],
    [
        'name' => esc_html__('Product List Carousel', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-plugin-product-list-carousel',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/plc_documentation/',
        'demo' => 'https://bestwpdeveloper.com/creative-product-list-carousel',
        'video' => 'https://youtu.be/jKLkSQt6fC4',
        'free_pro' => true,
        'new' => false,
    ],
    [
        'name' => esc_html__('Product Timeline', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-plugin-product-timeline',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/woopt_documentation/',
        'demo' => 'https://bestwpdeveloper.com/product-timeline',
        'video' => 'https://youtu.be/dnjtTbxsxk0',
        'free_pro' => true,
        'new' => false,
    ],
    [
        'name' => esc_html__('Related Product', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-plugin-related-product',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/wrp_documentation/',
        'demo' => 'https://bestwpdeveloper.com/woocommerce-related-product',
        'video' => 'https://youtu.be/4EmvvXsxDk8',
        'free_pro' => true,
        'new' => false,
    ],
    [
        'name' => esc_html__('Product Category Carousel', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-plugin-product-category-carousel',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/pcc_documentation/',
        'demo' => 'https://bestwpdeveloper.com/product-category-carousel',
        'video' => 'https://youtu.be/I6OlS6LPdxc',
        'free_pro' => true,
        'new' => false,
    ],
    [
        'name' => esc_html__('Featured Product', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-plugin-featured-product',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/wfpg_documentation/',
        'demo' => 'https://bestwpdeveloper.com/featured-product',
        'video' => 'https://youtu.be/O2ti4GlDUzY',
        'free_pro' => true,
        'new' => false,
    ],
    [
        'name' => esc_html__('Product Compare', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-plugin-product-compare',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/bwpc_documentation/',
        'demo' => 'https://bestwpdeveloper.com/woocommerece-product-compare/',
        'video' => 'https://youtu.be/2pep2x9TP8Y',
        'free_pro' => false,
        'new' => true,
    ],
    [
        'name' => esc_html__('Category Gallery', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-plugin-woo-cat-gallery',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/wcg_documentation/',
        'demo' => 'https://bestwpdeveloper.com/woocommerce-category-gallery/',
        'video' => 'https://youtu.be/_VVKmrtnQZc',
        'free_pro' => false,
        'new' => false,
    ],
    [
        'name' => esc_html__('Product Multi Action', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-plugin-woop-multi-action',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/wpma_documentation/',
        'demo' => 'https://bestwpdeveloper.com/woocommerce-product-multi-action/',
        'video' => 'https://youtu.be/fHpoRcb1jVI',
        'free_pro' => false,
        'new' => true,
    ],
    [
        'name' => esc_html__('Product Wish Action', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-plugin-woop-wish-cont',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/wpma_documentation/',
        'demo' => 'https://bestwpdeveloper.com/woocommerce-product-multi-action/',
        'video' => 'https://youtu.be/fHpoRcb1jVI',
        'free_pro' => false,
        'new' => true,
    ],
    [
        'name' => esc_html__('Product Vendors', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-woop-vendors',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/wpv_documentation/',
        'demo' => 'https://bestwpdeveloper.com/woocommerce-product-vendors/',
        'video' => 'https://youtu.be/nKoJK8lB8PU',
        'free_pro' => false,
        'new' => true,
    ],
    [
        'name' => esc_html__('3D Product Layout', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-twpx',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/3dwpl_documentation/',
        'demo' => 'https://bestwpdeveloper.com/3d-woocommerce-product-layout/',
        'video' => 'https://youtu.be/tfw9YrPjTuM',
        'free_pro' => false,
        'new' => true,
    ],
    [
        'name' => esc_html__('Special Day Offer', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-special-day-offer',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/special-day-offer/',
        'demo' => 'https://bestwpdeveloper.com/special-day-offer/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => true,
    ]
];
// ====================================================
// For extensions 
$extentionsWidgets = [
    [
        'name' => esc_html__('Text Tooltip', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-extn-tooltip',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/extensions/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
    ],
    [
        'name' => esc_html__('Wrap Link', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-extn-link',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/extensions/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
    ],
    [
        'name' => esc_html__('Content Protection', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-extn-protctn',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/extensions/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
    ],
    [
        'name' => esc_html__('CSS Transform', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-csstrnsm',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/extensions/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
    ],
    [
        'name' => esc_html__('Floating Animation', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-flanime',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/extensions/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
    ],
    [
        'name' => esc_html__('3D Text', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-3d-text',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/extensions/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
    ],
    [
        'name' => esc_html__('Notation', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-notation',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/extensions/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
    ],
    [
        'name' => esc_html__('Confetti Effects', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-confetti-effects',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/extensions/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
    ],
    [
        'name' => esc_html__('Cursor Effects', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-cursor-effects',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/extensions/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
    ],
    [
        'name' => esc_html__('Reveal Effects', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-reveal-effects',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/extensions/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
    ],
    [
        'name' => esc_html__('Tile Scroll', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-tile-scroll',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/extensions/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
    ],
    [
        'name' => esc_html__('Section Sticky', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-section-sticky',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/extensions/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
    ],
    [
        'name' => esc_html__('Scroll Box', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-scroll-box',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/extensions/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
    ],
    [
        'name' => esc_html__('Background Particles', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-background-particles',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/extensions/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
    ],
    [
        'name' => esc_html__('Cross Domain', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-xd-copy',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/extensions/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
    ],
    [
        'name' => esc_html__('Background Parallax', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-section-parallax',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/extensions/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
    ],
    [
        'name' => esc_html__('Gradient Animated Background', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-gra-anim-bg',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/extensions/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
    ],
    [
        'name' => esc_html__('Backdrop Filter', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-backdrop-filter',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/extensions/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
    ],
    [
        'name' => esc_html__('Line Grid', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-line-grid',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/extensions/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
    ],
    [
        'name' => esc_html__('Cursor Image Parallax', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-cursor-img-parallax',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/extensions/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
    ]
];
// For integrations
$inteGrations = [
    [
        'name'=>esc_html__('Advanced blog post block',BWDEB_PLUGIN_TD),
        'description'=>esc_html__('The Advanced Blog Post Block is a powerful Gutenberg Block that enhances your website\'s post display with advanced customization options.',BWDEB_PLUGIN_TD),
        'img'=>esc_url(plugin_dir_url( __FILE__ ).'../../../assets/admin/dashboard/images/Icon.svg'),
        'url'=>'https://wordpress.org/plugins/advanced-blog-post-block/',
    ],
    [
        'name'=>esc_html__('Product Estimated Shipping Date',BWDEB_PLUGIN_TD),
        'description'=>esc_html__('Plugin displays estimated shipping dates for WooCommerce products.',BWDEB_PLUGIN_TD),
        'img'=>esc_url(plugin_dir_url( __FILE__ ).'../../../assets/admin/dashboard/images/Icon1.svg'),
        'url'=>'https://codecanyon.net/item/bwd-product-estimated-shipping-date-plugin-for-woocommerce/47990580',
    ],
    [
        'name'=>esc_html__('WordPress File Management System',BWDEB_PLUGIN_TD),
        'description'=>esc_html__('The WordPress File Management System facilitates seamless organization, upload, and management of files within WordPress websites, streamlining content management tasks effectively.',BWDEB_PLUGIN_TD),
        'img'=>esc_url(plugin_dir_url( __FILE__ ).'../../../assets/admin/dashboard/images/Icon2.svg'),
        'url'=>'https://codecanyon.net/item/bwd-wordpress-file-management-system/49712228',
    ],
    [
        'name'=>esc_html__('Product Custom Size Guide',BWDEB_PLUGIN_TD),
        'description'=>esc_html__('The Product Custom Size Guide plugin facilitates creating personalized size guides for products, enhancing customer shopping experiences by providing accurate sizing information.',BWDEB_PLUGIN_TD),
        'img'=>esc_url(plugin_dir_url( __FILE__ ).'../../../assets/admin/dashboard/images/Icon3.svg'),
        'url'=>'https://codecanyon.net/item/bwd-product-custom-size-guide-for-woocommerce/49409126',
    ]
];
// For extra settings
$extraStng = [
    [
        'name' => esc_html__('Duplicate', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-duplicate',
        'logo' => '../../assets/admin/dashboard/images/Icon4.svg',
        'description' => esc_html__('This functionality is useful for content creators who need to replicate a particular post layout, structure, or set of metadata without starting from scratch.', BWDEB_PLUGIN_TD),
        'demo' => 'https://bestwpdeveloper.com/extensions/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
    ],
    [
        'name' => esc_html__('Live Copy', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-live-copy',
        'logo' => '../../assets/admin/dashboard/images/Icon5.svg',
        'description' => esc_html__('Live Copy for WordPress post types refers to the functionality that allows users to duplicate or clone existing posts, pages, or custom post types, including their content, metadata, and settings, in real-time.', BWDEB_PLUGIN_TD),
        'demo' => 'https://bestwpdeveloper.com/extensions/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
    ],
    [
        'name' => esc_html__('Custom JS & CSS', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-custom-jscss',
        'logo' => '../../assets/admin/dashboard/images/Icon6.svg',
        'description' => esc_html__('Custom JS & CSS functionality is often provided by plugins and can be used to enhance the site\'s appearance and functionality.', BWDEB_PLUGIN_TD),
        'demo' => 'https://bestwpdeveloper.com/extensions/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
    ],
    [
        'name' => esc_html__('Header Builder', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-header-builder',
        'logo' => '../../assets/admin/dashboard/images/Icon1.svg',
        'description' => esc_html__('Elementor Header Builder creates customizable headers with drag-and-drop ease.', BWDEB_PLUGIN_TD),
        'demo' => 'https://bestwpdeveloper.com/extensions/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
    ],
    [
        'name' => esc_html__('Footer Builder', BWDEB_PLUGIN_TD),
        'id' => 'bwdeb-footer-builder',
        'logo' => '../../assets/admin/dashboard/images/Icon7.svg',
        'description' => esc_html__('Elementor Footer Builder creates customizable footers with drag-and-drop ease.', BWDEB_PLUGIN_TD),
        'demo' => 'https://bestwpdeveloper.com/extensions/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
    ]
];
// For license
$getLicense = [
    [
        'id'=>'feature-one',
        'name'=>esc_html__('All Widgets & Presets',BWDEB_PLUGIN_TD),
        'free'=>'yes',
        'pro'=>'yes',
    ],
    [
        'id'=>'feature-two3',
        'name'=>esc_html__('General Widgets',BWDEB_PLUGIN_TD),
        'free'=>'35 Widgets',
        'pro'=>'98 Widgets',
    ],
    [
        'id'=>'feature-two2',
        'name'=>esc_html__('Extensions ('.count($extentionsWidgets).')',BWDEB_PLUGIN_TD),
        'free'=>'yes',
        'pro'=>'yes',
    ],
    [
        'id'=>'feature-two4',
        'name'=>esc_html__('CV Builder ('.count($cvWidgets).')',BWDEB_PLUGIN_TD),
        'free'=>'yes',
        'pro'=>'yes',
    ],
    [
        'id'=>'feature-two5',
        'name'=>esc_html__('Hero Sections ('.($i-1).')',BWDEB_PLUGIN_TD),
        'free'=>'yes',
        'pro'=>'yes',
    ],
    [
        'id'=>'feature-two6',
        'name'=>esc_html__('Post Widgets',BWDEB_PLUGIN_TD),
        'free'=>'09 Widgets',
        'pro'=>'12 Widgets',
    ],
    [
        'id'=>'feature-two7',
        'name'=>esc_html__('Product Widgets',BWDEB_PLUGIN_TD),
        'free'=>'13 Widgets',
        'pro'=>'19 Widgets',
    ],
    [
        'id'=>'feature-three',
        'name'=>esc_html__('Extra Settings ('.count($extraStng).')',BWDEB_PLUGIN_TD),
        'free'=>'yes',
        'pro'=>'yes',
    ],
    [
        'id'=>'feature-two',
        'name'=>esc_html__('All Widgets',BWDEB_PLUGIN_TD),
        'free'=>'Two Presets Available',
        'pro'=>'All Presets Available',
    ],
    [
        'id'=>'feature-five',
        'name'=>esc_html__('Live Copy',BWDEB_PLUGIN_TD),
        'free'=>'yes',
        'pro'=>'yes',
    ],
    [
        'id'=>'feature-five2',
        'name'=>esc_html__('Custom JS & CSS',BWDEB_PLUGIN_TD),
        'free'=>'yes',
        'pro'=>'yes',
    ],
    [
        'id'=>'feature-five3',
        'name'=>esc_html__('Duplicate',BWDEB_PLUGIN_TD),
        'free'=>'yes',
        'pro'=>'yes',
    ],
    [
        'id'=>'feature-five4',
        'name'=>esc_html__('Background Parallax',BWDEB_PLUGIN_TD),
        'free'=>'yes',
        'pro'=>'yes',
    ],
    [
        'id'=>'feature-five5',
        'name'=>esc_html__('Confetti Effects',BWDEB_PLUGIN_TD),
        'free'=>'yes',
        'pro'=>'yes',
    ],
    [
        'id'=>'text-tooltip',
        'name'=>esc_html__('Text Tooltip',BWDEB_PLUGIN_TD),
        'free'=>'yes',
        'pro'=>'yes',
    ],
    [
        'id'=>'wrap-link',
        'name'=>esc_html__('Wrap Link',BWDEB_PLUGIN_TD),
        'free'=>'yes',
        'pro'=>'yes',
    ],
    [
        'id'=>'content-protection',
        'name'=>esc_html__('Content Protection',BWDEB_PLUGIN_TD),
        'free'=>'yes',
        'pro'=>'yes',
    ],
    [
        'id'=>'css-transform',
        'name'=>esc_html__('CSS Transform',BWDEB_PLUGIN_TD),
        'free'=>'yes',
        'pro'=>'yes',
    ],
    [
        'id'=>'floating-animation',
        'name'=>esc_html__('Floating Animation',BWDEB_PLUGIN_TD),
        'free'=>'yes',
        'pro'=>'yes',
    ],
    [
        'id'=>'3d-text',
        'name'=>esc_html__('3D Text',BWDEB_PLUGIN_TD),
        'free'=>'yes',
        'pro'=>'yes',
    ],
    [
        'id'=>'notation',
        'name'=>esc_html__('Notation',BWDEB_PLUGIN_TD),
        'free'=>'yes',
        'pro'=>'yes',
    ],
    [
        'id'=>'cursor-effects',
        'name'=>esc_html__('Cursor Effects',BWDEB_PLUGIN_TD),
        'free'=>'yes',
        'pro'=>'yes',
    ],
    [
        'id'=>'reveal-effects',
        'name'=>esc_html__('Reveal Effects',BWDEB_PLUGIN_TD),
        'free'=>'yes',
        'pro'=>'yes',
    ],
    [
        'id'=>'tile-scroll',
        'name'=>esc_html__('Tile Scroll',BWDEB_PLUGIN_TD),
        'free'=>'yes',
        'pro'=>'yes',
    ],
    [
        'id'=>'section-sticky',
        'name'=>esc_html__('Section Sticky',BWDEB_PLUGIN_TD),
        'free'=>'yes',
        'pro'=>'yes',
    ],
    [
        'id'=>'scroll-box',
        'name'=>esc_html__('Scroll Box',BWDEB_PLUGIN_TD),
        'free'=>'yes',
        'pro'=>'yes',
    ],
    [
        'id'=>'3d-text',
        'name'=>esc_html__('Background Particles',BWDEB_PLUGIN_TD),
        'free'=>'yes',
        'pro'=>'yes',
    ],
    [
        'id'=>'gradient-animated-background',
        'name'=>esc_html__('Gradient Animated Background',BWDEB_PLUGIN_TD),
        'free'=>'yes',
        'pro'=>'yes',
    ],
    [
        'id'=>'backdrop-filter',
        'name'=>esc_html__('Backdrop Filter',BWDEB_PLUGIN_TD),
        'free'=>'yes',
        'pro'=>'yes',
    ],
    [
        'id'=>'line-grid',
        'name'=>esc_html__('Line Grid',BWDEB_PLUGIN_TD),
        'free'=>'yes',
        'pro'=>'yes',
    ],
    [
        'id'=>'cursor-image-parallax',
        'name'=>esc_html__('Cursor Image Parallax',BWDEB_PLUGIN_TD),
        'free'=>'yes',
        'pro'=>'yes',
    ]
];

$widgetTypes = array(
    'bwdeb-plugin-back-to-top'=>'BWDBackToTop',
    // 'bwdeb-plugin-creative-tab'=>'bwdadt-creative-table',
    'bwdeb-plugin-testimonials'=>'bwdtbtTestimonials',
    'bwdeb-plugin-post-accordion'=>'BlogPostAccordions',
    'bwdeb-plugin-accordion'=>'Accordion',
    'bwdeb-plugin-product-accordion'=>'WooCommerceProductAccordion',
    'bwdeb-plugin-animated-heading'=>'BWDAnimatedHeading',
    'bwdeb-plugin-animated-link'=>'bwdal-animated-link',
    'bwdeb-plugin-author-bio'=>'BWDABAuthorBio',
    'bwdeb-plugin-blockquote'=>'bwdeb-blockquote-addons',
    'bwdeb-plugin-post-list'=>'BlogList',
    'bwdeb-plugin-business-hours'=>'bwdbh-business-hours',
    'bwdeb-plugin-info-download-button'=>'bwdidb-info-download-button',
    'bwdeb-plugin-call-to-action'=>'CallToAction',
    'bwdeb-plugin-product-category-carousel'=>'bwdcp-catproduct',
    'bwdeb-plugin-product-category-grid'=>'thecpg-catproduct',
    'bwdeb-plugin-product-category-tiles'=>'ProductTilesCat',
    'bwdeb-plugin-circle-info'=>'bwdci-circle-info',
    'bwdeb-plugin-click-to-contact'=>'bwdctc-clicktocall',
    'bwdeb-plugin-image-compare'=>'NameImageCompare',
    'bwdeb-plugin-content-switcher'=>'bwdcs-content-switcher',
    'bwdeb-plugin-countdown'=>'BWDCDCountdown',
    'bwdeb-plugin-counter'=>'bwdcCounter',
    'bwdeb-plugin-coupon-code'=>'bwbcod-coupon-code',
    'bwdeb-plugin-creative-button'=>'NameCreativeButtons',
    'bwdeb-plugin-data-table'=>'bwdeb-data-table',
    'bwdeb-plugin-fancy-heading'=>'bwdst-fancy-heading',
    'bwdeb-plugin-filterable-gallery'=>'NameFilterableGallery',
    'bwdeb-plugin-flip-box-carousel'=>'bwdfb-flip-box-Carousel',
    'bwdeb-plugin-dual-heading'=>'NameDualHeading',
    'bwdeb-plugin-icon-box'=>'bwbib-icon-box',
    'bwdeb-plugin-ihover'=>'wppih-iHover-Effect',
    'bwdeb-plugin-image-scroll'=>'bwdimagescroll',
    'bwdeb-plugin-image-shape'=>'bwdim-image-shape',
    'bwdeb-plugin-post-image-accordion'=>'BlogPostImageAccordion',
    'bwdeb-plugin-image-accordion'=>'bwdskimageaccordion',
    'bwdeb-plugin-product-image-accordion'=>'bwdimageaccordion',
    'bwdeb-plugin-image-hover-effect'=>'bwbih-image-hover',
    'bwdeb-plugin-image-stack-group'=>'bwdis_image_stack',
    'bwdeb-plugin-image-swap'=>'BWDISImageSwap',
    'bwdeb-plugin-creative-list'=>'bwdbl_list',//
    'bwdeb-plugin-logo-carousel'=>'bwdlc-Logo-Carousel',
    'bwdeb-plugin-logo-filter'=>'Bwd_logo_Filter',
    'bwdeb-plugin-logo-grid'=>'Logo_Grid',
    'bwdeb-plugin-masking-video'=>'MaskingVideo',
    'bwdeb-plugin-masking-effect'=>'NameMaskingEffects',
    'bwdeb-plugin-map-masking'=>'NameMapMasking',
    'bwdeb-plugin-news-ticker'=>'ptnticker-newsticker',
    'bwdeb-plugin-photo-stack'=>'bwdps_photo_stack',
    'bwdeb-plugin-effective-pre-loader'=>'EffectivePreLoader',
    'bwdeb-plugin-pricing-table'=>'bwbpt-price',
    'bwdeb-plugin-related-product'=>'woocrp-product-carousel',
    'bwdeb-plugin-product-carousel'=>'wppgpc-product-carousel',
    'bwdeb-plugin-product-list-carousel'=>'CreativeProductsListcarousel',
    'bwdeb-plugin-product-grid'=>'CreativeProductsGrid',
    'bwdeb-plugin-product-list'=>'CreativeProductsList',
    'bwdeb-plugin-product-tiles'=>'WooCProductsTiles',
    'bwdeb-plugin-featured-product'=>'WooFeaturedProductGridTypes',
    'bwdeb-plugin-profile-card'=>'bwbpc-profile-card',
    'bwdeb-plugin-progress-bar'=>'BWDPBProgressBar',
    'bwdeb-plugin-promo-box'=>'bwdeeo_promo_box',
    'bwdeb-plugin-service-flip-box'=>'NameServiceFlipBox',
    'bwdeb-plugin-service-showcase'=>'NameServiceShowcase',
    'bwdeb-plugin-single-post-slider'=>'teps-swiperslider',
    'bwdeb-plugin-social-icon'=>'bwdsi-social-icon',
    'bwdeb-plugin-step-flip-box'=>'NameStepFlipBox',
    'bwdeb-plugin-awesome-step'=>'bwbasawesomestep',
    'bwdeb-plugin-background-switcher'=>'bwdsb-switchbackground',
    'bwdeb-plugin-creative-tab'=>'NameTabsZone',// right
    'bwdeb-plugin-team-flip-box'=>'NameTeamFlipBox',
    'bwdeb-plugin-team-carousel'=>'bwdtmc-teammember-carousel',//
    'bwdeb-plugin-post-timeline'=>'ThePostTimeline',
    'bwdeb-plugin-timeline'=>'BWD Timeline',
    'bwdeb-plugin-unfold'=>'bwduf-unfoldcontent',
    'bwdeb-plugin-video-popup'=>'BWD_Video_Popup',
    'bwdeb-plugin-webinar-info'=>'bwdwi-webinar-info',
    'bwdeb-plugin-code-highlighter'=>'CodEntorSyntaxHighlighter',
    'bwdeb-plugin-dual-button'=>'NameDualButtons',
    'bwdeb-plugin-breadcrumb'=>'GreatestBreadcrumb',
    'bwdeb-plugin-unique-headers'=>'TheNavMenu',
    'bwdeb-plugin-post-grid'=>'NameBlog',
    'bwdeb-plugin-masonary-blog-post'=>'MasonryBlogPosts',
    'bwdeb-plugin-post-tiles'=>'BlogPost_Tiles',
    'bwdeb-plugin-team-carousel2'=>'MeetTheTeamCarousel',//==
    'bwdeb-plugin-meet-the-team'=>'MeetTheTeam',
    'bwdeb-plugin-social-share'=>'UniqueSocialShare',
    'bwdeb-plugin-product-timeline'=>'WooCommerceProductsTimeline',
    // pro
    'bwdeb-plugin-honeycombs' => 'bwdhcx-honeycombs',
    'bwdeb-plugin-popup' => 'bwdmp_Modal_Popup',
    'bwdeb-plugin-advanced-slider' => 'bwdads-swiperslider',
    'bwdeb-plugin-slide-anything' => 'bwdsas-anything-slide',
    'bwdeb-plugin-image-hotspot' => 'bwbihp-imghotspot',
    'bwdeb-plugin-unfold' => 'bwduf-unfoldcontent',
    'bwdeb-plugin-lottie-animation' => 'EffectiveLottieAnimation',
    'bwdeb-plugin-bar-chart' => 'bwdpcb-bar-piechart',
    'bwdeb-plugin-lord-icon' => 'PowerfulLordiconsAnimation',
    'bwdeb-plugin-cart-flipper' => 'bwdcfpx-card-flipper-pro',
    'bwdeb-plugin-ajax-data-table' => 'bwdadt-creative-table',
    'bwdeb-plugin-con-swi-pls' => 'bwdcspx-content-switch-plus',
    'bwdeb-plugin-img-rev-widg' => 'bwdirax-image-reveal-animation',
    'bwdeb-plugin-img-unfold-kit' => 'bwdiukx-kit-unfold-image',
    'bwdeb-plugin-modern-feature-list' => 'bwdmflx-modern-feature-list',
    'bwdeb-plugin-offcanvasmagic' => 'bwdosmx-offcanvas-slide-magic',
    'bwdeb-plugin-privacy-content-locker' => 'bwdpclx-PrivacyContentLocker',
    'bwdeb-plugin-viewpdf' => 'bwdpdfx-view-pdf-clear',
    'bwdeb-plugin-progress-master-kit' => 'bwdpmkx-progress-master-kit',
    'bwdeb-plugin-restaurant-price-menu' => 'bwdrpmx-restaurant-price-menu',
    'bwdeb-plugin-sales-promotion-offer' => 'bwdspox-promotion-sales-offer',
    'bwdeb-plugin-profile-showcas' => 'bwdsypx-showcase-your-profile',
    'bwdeb-plugin-tooltip-mastery' => 'bwdttmx-tooltip-mastery',
    'bwdeb-employee-profile-identity' => 'bwdepix-employe-profile-identity',
    'bwdeb-horizontal-timeline-slider' => 'bwdhtsx-horizontal-slider-timeline',
    'bwdeb-product-features-w' => 'bwdspfx-showcase-profea',
    'bwdeb-threesixty-rotation-view' => 'bwdtsrx-threesixty-rotation-view',
    'bwdeb-widget-template' => 'FAQForgeName',
    'bwdeb-pssx' => 'bwdpssx-pricing-switcher-scheme',
    'bwdeb-blmx1' => 'bwdblmx-bio-about-me',
    'bwdeb-blmx2' => 'bwdblmx-bio-link-maker',
    'bwdeb-blmx3' => 'bwdblmx-bio-social-media',
    'bwdeb-svpx' => 'bwdsvpx-sticky-video-prime',
    'bwdeb-txsx' => 'bwdtxsx-tabify-xpert-suite',
    'bwdeb-vsix' => 'bwdvsix-vertical-split-slideshow',
    // CV builder
    'bwdeb-plugin-cv-builder' => 'bwdcv-cv-builder',
    'bwdeb-plugin-cv-about' => 'bwdcv-cv-builder-about',
    'bwdeb-plugin-cv-contact' => 'bwdcv-cv-builder-contact',
    'bwdeb-plugin-cv-education' => 'bwdcv-cv-builder-education',
    'bwdeb-plugin-cv-experience' => 'bwdcv-cv-builder-experience',
    'bwdeb-plugin-cv-footer' => 'bwdcv-cv-builder-footer',
    'bwdeb-plugin-cv-header' => 'bwdcv-cv-builder-header',
    'bwdeb-plugin-cv-hobby' => 'bwdcv-cv-builder-hobby',
    'bwdeb-plugin-cv-language' => 'bwdcv-cv-builder-language',
    'bwdeb-plugin-cv-reference' => 'bwdcv-cv-builder-reference',
    'bwdeb-plugin-cv-skill' => 'bwdcv-cv-builder-skill',
    // Hero Section
    'bwdeb-check-hero-widget1' => 'bwdhsx-hero-style1',
    'bwdeb-check-hero-widget2' => 'bwdhsx-hero-style2',
    'bwdeb-check-hero-widget3' => 'bwdhsx-hero-style3',
    'bwdeb-check-hero-widget4' => 'bwdhsx-hero-style4',
    'bwdeb-check-hero-widget5' => 'bwdhsx-hero-style5',
    'bwdeb-check-hero-widget6' => 'bwdhsx-hero-style6',
    'bwdeb-check-hero-widget7' => 'bwdhsx-hero-style7',
    'bwdeb-check-hero-widget8' => 'bwdhsx-hero-style8',
    'bwdeb-check-hero-widget9' => 'bwdhsx-hero-style9',
    'bwdeb-check-hero-widget10' => 'bwdhsx-hero-style10',
    'bwdeb-check-hero-widget11' => 'bwdhsx-hero-style11',
    'bwdeb-check-hero-widget12' => 'bwdhsx-hero-style12',
    'bwdeb-check-hero-widget13' => 'bwdhsx-hero-style13',
    //
    'bwdeb-plugin-creative-post-carousel'=>'bwdbpc-blogpost-carousel',
    'bwdeb-post-prestige-portfolio'=>'bwdpppx-post-prestige-portfolio',
    'bwdeb-apostst'=>'AdvancedPostsTab',
    //
    'bwdeb-plugin-product-compare'=>'bwdwpcproductcompare',
    'bwdeb-plugin-woo-cat-gallery'=>'bwdwcgx-woocat-gallery-pro',
    'bwdeb-plugin-woop-multi-action'=>'bwdwpmxwooproductgrid',
    'bwdeb-plugin-woop-wish-cont'=>'bwd-wishlist-count',
    'bwdeb-woop-vendors'=>'bwdwpvx-product-vendors',
    'bwdeb-twpx'=>'bwdtwpx-3D-Product-layout',
    'bwdeb-special-day-offer'=>'SpecialDayOffer',
    'bwdeb-random-image'=>'bwdrmx-random-image',
    'bwdeb-mega-menu'=>'MegaMenuMaster',
);


